/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type BackgroundImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "heroSlide.backgroundImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type Avatar = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "avatar.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ServiceCardImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "serviceCard.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type Icon = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "icon.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type BeforeImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "beforeImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type AfterImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "afterImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type BlogSection = {
  _type: 'blogSection'
  eyebrow?: string
  heading?: string
  subheading?: string
  maxPosts?: 2 | 3 | 4 | 6
  theme?: 'light' | 'dark'
}

export type BeforeAfter = {
  _type: 'beforeAfter'
  eyebrow?: string
  heading?: string
  subheading?: string
  items?: Array<{
    title?: string
    description?: string
    beforeImage?: BeforeImage
    afterImage?: AfterImage
    _type: 'beforeAfterItem'
    _key: string
  }>
  theme?: 'light' | 'dark'
}

export type Gallery = {
  _type: 'gallery'
  eyebrow?: string
  heading?: string
  subheading?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'galleryImage'
    _key: string
  }>
  columns?: 2 | 3 | 4
  theme?: 'light' | 'dark'
}

export type ContactForm = {
  _type: 'contactForm'
  title?: string
  intro?: string
  phone?: string
  email?: string
  location?: string
  services?: Array<string>
}

export type ProcessSection = {
  _type: 'processSection'
  eyebrow?: string
  heading: string
  subheading?: string
  steps?: Array<{
    icon?:
      | 'Phone'
      | 'ClipboardList'
      | 'Palette'
      | 'Ruler'
      | 'PaintRoller'
      | 'Paintbrush'
      | 'Sparkles'
      | 'BadgeCheck'
      | 'MessageSquare'
      | 'Calendar'
      | 'Search'
      | 'Truck'
      | 'User'
      | 'FileText'
      | 'CheckCircle2'
      | 'Star'
      | 'ShieldCheck'
    title: string
    description?: string
    _type: 'processStep'
    _key: string
  }>
  theme?: 'light' | 'dark'
}

export type MainServiceGrid = {
  _type: 'mainServiceGrid'
  eyebrow?: string
  heading: string
  subheading?: string
  items?: Array<{
    icon?:
      | 'PaintRoller'
      | 'Paintbrush'
      | 'PaintBucket'
      | 'Palette'
      | 'Brush'
      | 'SprayCan'
      | 'Ruler'
      | 'Layers'
      | 'Sparkles'
      | 'Home'
      | 'Building2'
      | 'ShieldCheck'
      | 'Clock'
      | 'Star'
      | 'CheckCircle2'
    title: string
    description?: string
    bullets?: Array<string>
    cta?: Button
    _type: 'serviceItem'
    _key: string
  }>
  theme?: 'light' | 'dark'
  columns?: 2 | 3 | 4
}

export type IntroOverviewSection = {
  _type: 'introOverviewSection'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  stats?: Array<{
    value?: string
    label?: string
    _type: 'stat'
    _key: string
  }>
  checklist?: Array<string>
  cta?: Button
  secondaryCta?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  imageAlignment?: 'left' | 'right'
}

export type Cta = {
  _type: 'cta'
  eyebrow?: string
  heading?: string
  subheading?: string
  primaryButton?: Button
  secondaryButton?: Button
  theme?: 'brand' | 'dark' | 'light'
  textAlignment?: 'center' | 'left'
}

export type Faq = {
  _type: 'faq'
  eyebrow?: string
  heading?: string
  subheading?: string
  items?: Array<{
    question?: string
    answer?: BlockContentTextOnly
    _type: 'faqItem'
    _key: string
  }>
  theme?: 'light' | 'dark'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type AreasWeCover = {
  _type: 'areasWeCover'
  eyebrow?: string
  heading?: string
  subheading?: string
  areas?: Array<{
    name?: string
    page?: PageReference
    _type: 'area'
    _key: string
  }>
  theme?: 'light' | 'dark'
}

export type EmergencyCtaStrip = {
  _type: 'emergencyCtaStrip'
  heading?: string
  subheading?: string
  phoneNumber?: string
  button?: Button
  theme?: 'brand' | 'dark' | 'light'
}

export type WhyChooseUs = {
  _type: 'whyChooseUs'
  eyebrow?: string
  heading?: string
  subheading?: string
  reasons?: Array<{
    title?: string
    description?: string
    icon?: Icon
    _type: 'reason'
    _key: string
  }>
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  button?: Button
  theme?: 'light' | 'dark'
  imageAlignment?: 'left' | 'right'
}

export type ServiceCards = {
  _type: 'serviceCards'
  eyebrow?: string
  heading?: string
  subheading?: string
  cards?: Array<{
    title?: string
    description?: string
    image?: ServiceCardImage
    button?: Button
    _type: 'serviceCard'
    _key: string
  }>
  theme?: 'light' | 'dark'
  columns?: 2 | 3 | 4
}

export type Testimonials = {
  _type: 'testimonials'
  eyebrow?: string
  heading?: string
  items?: Array<{
    quote?: string
    authorName?: string
    authorLocation?: string
    rating?: 1 | 2 | 3 | 4 | 5
    avatar?: Avatar
    _type: 'testimonialItem'
    _key: string
  }>
  reviewsUrl?: string
  leaveReviewUrl?: string
  theme?: 'light' | 'dark'
}

export type HeroCarousel = {
  _type: 'heroCarousel'
  slides?: Array<{
    eyebrow?: string
    heading: string
    subheading?: string
    primaryButton?: Button
    secondaryButton?: Button
    backgroundImage?: BackgroundImage
    theme?: 'dark' | 'light'
    _type: 'heroSlide'
    _key: string
  }>
  textAlignment?: 'left' | 'center'
  autoPlay?: boolean
  interval?: number
}

export type HeroBanner = {
  _type: 'heroBanner'
  eyebrow?: string
  heading?: string
  subheading?: string
  primaryButton?: Button
  secondaryButton?: Button
  trustBadges?: Array<{
    icon?: 'ShieldCheck' | 'Clock' | 'Star' | 'Tag'
    label?: string
    _type: 'trustBadge'
    _key: string
  }>
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  textAlignment?: 'left' | 'center'
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  canonical?: string
  noIndex?: boolean
  noFollow?: boolean
  hideFromSitemap?: boolean
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  ogTitle?: string
  ogDescription?: string
  keywords?: Array<string>
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page?: PageReference
    post?: PostReference
    openInNewTab?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type AreaReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'area'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type ServiceArea = {
  _id: string
  _type: 'serviceArea'
  _createdAt: string
  _updatedAt: string
  _rev: string
  service: ServiceReference
  area: AreaReference
  localIntro: string
  projects: Array<
    {
      _key: string
    } & ProjectReference
  >
  localTestimonial?: {
    quote?: string
    authorName?: string
  }
  localFaqs?: Array<{
    question?: string
    answer?: string
    _type: 'faqItem'
    _key: string
  }>
  seo?: Seo
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  services: Array<
    {
      _key: string
    } & ServiceReference
  >
  area?: AreaReference
  locationLabel?: string
  summary: string
  body?: BlockContentTextOnly
  completedAt?: string
  featured?: boolean
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'galleryImage'
    _key: string
  }>
  beforeAfter?: Array<{
    label?: string
    beforeImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    afterImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    _type: 'beforeAfterPair'
    _key: string
  }>
  testimonial?: {
    quote?: string
    authorName?: string
    rating?: 1 | 2 | 3 | 4 | 5
  }
  seo?: Seo
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Area = {
  _id: string
  _type: 'area'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  h1?: string
  slug: Slug
  order?: number
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  intro: BlockContentTextOnly
  coverageNote?: string
  geo?: {
    latitude?: number
    longitude?: number
  }
  featuredServices?: Array<
    {
      _key: string
    } & ServiceReference
  >
  localTestimonials?: Array<{
    quote?: string
    authorName?: string
    authorLocation?: string
    rating?: 1 | 2 | 3 | 4 | 5
    _type: 'testimonial'
    _key: string
  }>
  faqs?: Array<{
    question?: string
    answer?: string
    _type: 'faqItem'
    _key: string
  }>
  seo?: Seo
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  h1?: string
  slug: Slug
  order?: number
  icon?:
    | 'PaintRoller'
    | 'Paintbrush'
    | 'PaintBucket'
    | 'Palette'
    | 'Brush'
    | 'SprayCan'
    | 'Ruler'
    | 'Layers'
    | 'Sparkles'
    | 'Home'
    | 'Building2'
  summary: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  overview?: BlockContentTextOnly
  trustSignals?: Array<{
    icon?: 'ShieldCheck' | 'Clock' | 'Star' | 'Tag' | 'BadgeCheck' | 'Sparkles'
    label: string
    _type: 'trustSignal'
    _key: string
  }>
  whatsIncluded?: Array<{
    title?: string
    description?: string
    _type: 'inclusion'
    _key: string
  }>
  steps?: Array<{
    icon?:
      | 'PaintRoller'
      | 'Paintbrush'
      | 'PaintBucket'
      | 'Palette'
      | 'Brush'
      | 'SprayCan'
      | 'Ruler'
      | 'Layers'
      | 'Sparkles'
      | 'Home'
      | 'Building2'
    title?: string
    description?: string
    _type: 'step'
    _key: string
  }>
  faqs?: Array<{
    question?: string
    answer?: string
    _type: 'faqItem'
    _key: string
  }>
  areasServed?: Array<
    {
      _key: string
    } & AreaReference
  >
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  seo?: Seo
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  seo?: Seo
  pageBuilder?: Array<
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & HeroCarousel)
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & ServiceCards)
    | ({
        _key: string
      } & WhyChooseUs)
    | ({
        _key: string
      } & EmergencyCtaStrip)
    | ({
        _key: string
      } & AreasWeCover)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & IntroOverviewSection)
    | ({
        _key: string
      } & MainServiceGrid)
    | ({
        _key: string
      } & ProcessSection)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & BeforeAfter)
    | ({
        _key: string
      } & BlogSection)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  columns?: Array<
    {
      _key: string
    } & FooterColumn
  >
  social?: Array<
    {
      _key: string
    } & SocialLink
  >
  legal?: Array<
    {
      _key: string
    } & LegalLink
  >
  copyright?: string
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  items?: Array<
    {
      _key: string
    } & NavItem
  >
  cta?: NavCta
}

export type NavCta = {
  _type: 'navCta'
  label: string
  link: Link
  variant?: 'primary' | 'secondary'
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  branding?: {
    siteTitle: string
    logo?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    whatsappNumber?: string
  }
  seo?: {
    title?: string
    description?: string
    metadataBase?: string
    ogImage?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    twitterHandle?: string
    robots?: {
      index?: boolean
      follow?: boolean
    }
  }
  structuredData?: {
    enabled?: boolean
    language?: string
    website?: {
      name?: string
      url: string
      enableSearchAction?: boolean
      searchUrlTemplate?: string
    }
    organization?: {
      name: string
      legalName?: string
      url: string
      description?: string
      slogan?: string
      foundingDate?: string
      awards?: Array<string>
      sameAs?: Array<string>
      logo?: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      image?: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      contact?: {
        phone?: string
        email?: string
        contactType?: string
        availableLanguage?: string
      }
      address?: {
        streetAddress?: string
        addressLocality?: string
        addressRegion?: string
        postalCode?: string
        addressCountry?: string
      }
      geo?: {
        latitude?: number
        longitude?: number
      }
      areaServed?: string
      founder?: {
        name?: string
        jobTitle?: string
        sameAs?: string
      }
      brands?: Array<{
        name: string
        url?: string
        logo?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        _type: 'schemaBrand'
        _key: string
      }>
    }
    localBusiness?: {
      enabled?: boolean
      serviceAreaOnly?: boolean
      priceRange?: string
      currency?: string
      openingHours?: Array<{
        dayOfWeek?: Array<string>
        opens?: string
        closes?: string
        _type: 'openingHoursSpec'
        _key: string
      }>
    }
    services?: Array<{
      title: string
      description?: string
      url?: string
      price?: string
      priceCurrency?: string
      _type: 'schemaService'
      _key: string
    }>
    areaServedCities?: Array<{
      title: string
      latitude?: number
      longitude?: number
      _type: 'servedCity'
      _key: string
    }>
    reviews?: {
      enabled?: boolean
      aggregateRating?: {
        ratingValue?: number
        reviewCount?: number
        bestRating?: number
        worstRating?: number
      }
      items?: Array<{
        author?: string
        rating?: number
        body?: string
        _type: 'schemaReview'
        _key: string
      }>
    }
  }
  theme?: {
    colorScheme: 'jw-orange-black' | 'blue-white' | 'black-white' | 'green-charcoal' | 'purple-dark'
    mode: 'light' | 'dark' | 'system'
    accent: 'solid' | 'outline' | 'soft'
    headingFont: 'inter' | 'poppins' | 'montserrat' | 'playfair'
    bodyFont: 'inter' | 'roboto' | 'opensans'
    monoFont: 'ibmplexmono' | 'jetbrainsmono' | 'spacemono'
    radius: 'none' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
    buttonStyle: 'pill' | 'rounded' | 'square'
    container?: 'default' | 'wide' | 'narrow'
  }
}

export type LegalLink = {
  _type: 'legalLink'
  label: string
  link: Link
}

export type SocialLink = {
  _type: 'socialLink'
  platform: string
  url: string
}

export type FooterColumn = {
  _type: 'footerColumn'
  title: string
  links?: Array<{
    label: string
    link: Link
    _type: 'footerLink'
    _key: string
  }>
}

export type NavItem = {
  _type: 'navItem'
  label: string
  kind: 'link' | 'dropdown'
  link?: Link
  children?: Array<{
    label: string
    description?: string
    link: Link
    _type: 'navChild'
    _key: string
  }>
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BackgroundImage
  | Avatar
  | ServiceCardImage
  | Icon
  | BeforeImage
  | AfterImage
  | BlogSection
  | BeforeAfter
  | Gallery
  | ContactForm
  | ProcessSection
  | MainServiceGrid
  | IntroOverviewSection
  | Cta
  | Faq
  | PageReference
  | AreasWeCover
  | EmergencyCtaStrip
  | WhyChooseUs
  | ServiceCards
  | Testimonials
  | HeroCarousel
  | HeroBanner
  | Seo
  | PostReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | ServiceReference
  | AreaReference
  | ProjectReference
  | ServiceArea
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Area
  | Service
  | Page
  | PersonReference
  | Post
  | Person
  | Footer
  | Navigation
  | NavCta
  | Settings
  | LegalLink
  | SocialLink
  | FooterColumn
  | NavItem
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
