import {
  BadgeCheck,
  Bath,
  Building2,
  Calendar,
  CheckCircle2,
  ClipboardList,
  Droplet,
  Fan,
  FileText,
  Flame,
  Hammer,
  Home,
  Leaf,
  MessageSquare,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  Palette,
  Phone,
  Plug,
  Ruler,
  Search,
  ShieldCheck,
  Siren,
  Sparkles,
  Star,
  Thermometer,
  Truck,
  User,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Covers the process-step icon enum (+ service icons) on the processSection schema. */
export const PROCESS_ICONS: Record<string, LucideIcon> = {
  Phone,
  ClipboardList,
  Palette,
  Ruler,
  PaintRoller,
  Paintbrush,
  Sparkles,
  BadgeCheck,
  MessageSquare,
  Calendar,
  Search,
  Truck,
  User,
  FileText,
  CheckCircle2,
  Star,
  ShieldCheck,
  // service icons (also selectable)
  Wrench,
  Hammer,
  Flame,
  Droplet,
  Zap,
  Thermometer,
  Siren,
  Bath,
  Home,
  Building2,
  PaintBucket,
  Plug,
  Fan,
  Leaf,
}

export const processIcon = (key?: string | null): LucideIcon =>
  (key && PROCESS_ICONS[key]) || CheckCircle2

/** 0-based index → "01", "02", … */
export const pad = (n: number) => String(n + 1).padStart(2, '0')
